AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A starter AWS Lambda function.
Parameters: 
    IdentityNameParameter: 
      Type: String
Resources:
  helloworldpython3:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.lambda_handler
      Runtime: python3.9
      CodeUri: .
      Description: A starter AWS Lambda function.
      MemorySize: 128
      Timeout: 10
      Policies:
        - SESSendBouncePolicy:
            IdentityName: !Ref IdentityNameParameter