name: carbon_tracker_env
channels:
  - conda-forge
dependencies:
  - python
  - pip
  # - npm
  
  - boto3
  - awscli
  - requests
  - pytest
  - pydantic
  
  # Computation
  - numpy
  - pandas

  # Plotting
  - matplotlib
  - seaborn

  # Debugging
  - jupyter
  - pylint
  - rope
  - black
  - isort

  - pip:
    - aws-cdk-lib
    - constructs